name: CI

on: [ push, pull_request ]

jobs:
  ci:
    name: Docker Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Compose
        uses: docker/setup-compose-action@v1

      - name: Build and start services with Docker Compose
        run: docker compose up -d

      - name: Wait for services to be ready
        run: sleep 15

      - name: Test application health
        run: |
          # Test if application responds
          curl -f http://localhost:3000 || exit 1

      - name: Test key endpoints
        run: |
          # Test static files are served (React app)
          curl -f -s http://localhost:3000/static/ > /dev/null || echo "Static endpoint not available"

          # Test API health (if available)
          curl -f -s http://localhost:3000/api/health > /dev/null || echo "API health endpoint not available"

      - name: Clean up
        run: docker compose down
