name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    name: Build and test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Compose
        uses: docker/setup-compose-action@v1

      - name: Build and start services with Docker Compose
        run: docker compose up -d

      - name: Wait for services to be ready
        run: sleep 15

      - name: Test application health
        run: |
          # Test if application responds
          curl -f http://localhost:3000 || exit 1

      - name: Clean up
        run: docker compose down
